### ISSUE TITLE
How to pick up the SWO output after board reset 

### ISSUE THREAD

**Issue by tomhepworth** [robertlong13/SWO-Parser#2]
Hi, thanks so much for this very helpful repo. 

I am trying to figure out how I can have the SWO output continue if I press the reset button on my nucleo board. This would be useful for some logging every early in my program startup.

Right now, the output halts after I press the reset button until openOCD reconfigures the board. Could you advise about how I might get this behaviour? 

Thanks

**Comment by robertlong13** [comment]
Unfortunately, I wrote this ages ago, and haven't done STM32 debugging at all in a few years.

The following is merely my best guess, and I don't have a Nucleo anymore to test anything.

OpenOCD has to reconfigure registers for the output to be work, and they default to disabled, I'm guessing you need to initiate the reset through OpenOCD and not the reset button. You might also need to configure it to halt on reset.

Sorry I can't be more help.

**Comment by tomhepworth** [comment]
Cheers for the response! No worries at all I had thought it was a long shot. I am new to OpenOCD/this sort of thing and I still am not sure how it all works. 

First I tried to reverse engineer the configuration by logging memory writes performed by OpenOCD in order to have the mcu configure itself as it starts up, but despite doing that and also trying to follow the example in the reference for configuring the SWO/ITM  I was not able to get any output.  I could see the light flickering on my STLink, so perhaps it was logging something, but nothing was appearing on the host. 

Thanks I will try resetting via openocd.
